import os
import shutil
import asyncio
import re
from typing import List, Optional
from dotenv import load_dotenv
from pydantic import BaseModel, Field

# Import ADK 2.0 core modules
import pathlib
from google.adk.agents import Agent
from google.adk import Workflow, Event
from google.adk.runners import InMemoryRunner
from google.adk.apps import App
from google.adk.skills import load_skill_from_dir
from google.adk.tools.skill_toolset import SkillToolset
from hooks import security_before_tool_callback

# Load local environment variables from the current directory
load_dotenv()

# ==========================================
# 1. Define Data Schemas
# ==========================================


class WorkflowInput(BaseModel):
    source_dir: str = Field(description="The directory path to scan and organize.")
    destination_dir: str = Field(
        description="The directory path where organized folders should be created."
    )


class FileInfo(BaseModel):
    filepath: str = Field(description="The absolute path to the file.")
    filename: str = Field(description="The basename of the file.")
    extension: str = Field(description="The file extension (e.g., .txt, .py).")
    snippet: str = Field(
        description="A brief text preview of the file contents or file type placeholder."
    )
    size_bytes: int = Field(description="File size in bytes.")


class ScanResult(BaseModel):
    source_dir: str = Field(description="The source directory scanned.")
    destination_dir: str = Field(description="The destination folder for organization.")
    files: List[FileInfo] = Field(description="List of detected files with metadata.")


class FileCategory(BaseModel):
    category_id: str = Field(
        description="A short, unique code for the category (e.g., 'python_scripts', 'financial_data')."
    )
    suggested_folder_name: str = Field(
        description="A descriptive, elegant folder name generated by the LLM (e.g., 'Core Python Utility Scripts', 'Q4 Quarterly Financials'). Do not use generic names like 'Python Files' or 'Documents'."
    )
    format_type: str = Field(
        description="General format group (e.g., Source Code, Document, Image, Spreadsheet)."
    )
    subject: str = Field(description="Identified core subject/topics of these files.")
    explanation: str = Field(
        description="Brief explanation of why these files belong in this group."
    )
    filepaths: List[str] = Field(
        description="List of absolute filepaths belonging to this category."
    )


class CategorizationResult(BaseModel):
    source_dir: str = Field(description="The source directory scanned.")
    destination_dir: str = Field(description="The target organized directory.")
    categories: List[FileCategory] = Field(
        description="List of identified categories and their assigned files."
    )


# ==============================================================================
# DESIGN PATTERN: Graph-Based Workflow Node 1
# ==============================================================================
# The Scan Directory Node is a deterministic, high-efficiency Python function.
# Its purpose is to crawl the file hierarchy, filter out massive development folders,
# and extract metadata along with small textual snippets.
#
# TOKEN-OPTIMIZATION HEURISTIC:
# Rather than sending whole documents to the Gemini model (which increases latency
# and cost), we parse file extensions and extract only the first 300 characters of
# text-based files. For binary or media files, we substitute content with descriptive
# placeholders (e.g., "[Binary/Media File: PNG]"). This maintains complete semantic
# context while preserving LLM context window tokens.
# ==============================================================================


def scan_directory_node(node_input: WorkflowInput) -> ScanResult:
    """
    BEHAVIOR:
    Crawls the target source directory recursively, excluding development directories,
    hidden files, and temporary caches. Captures file size, extension, and loads 
    a small textual preview snippet for semantic content classification.
    """
    source_dir = os.path.abspath(node_input.source_dir)
    destination_dir = os.path.abspath(node_input.destination_dir)

    print(f"\n[Step 1] Scanning files in directory: {source_dir}")

    files_list: List[FileInfo] = []
    ignored_folders = {
        ".venv",
        "venv",
        ".git",
        ".agents",
        "organized_output",
        "__pycache__",
        "node_modules",
    }

    if not os.path.exists(source_dir):
        raise ValueError(f"Source directory does not exist: {source_dir}")

    for root, dirs, files in os.walk(source_dir):
        # In-place modify dirs to skip ignored subdirectories recursively
        dirs[:] = [
            d for dirs_list in [dirs] for d in dirs_list if d not in ignored_folders
        ]

        # Avoid scanning files inside the destination directory if it is a subdirectory of source
        if os.path.commonpath([root, destination_dir]) == destination_dir:
            continue

        for file in files:
            filepath = os.path.join(root, file)
            # Skip hidden files
            if file.startswith("."):
                continue

            try:
                size_bytes = os.path.getsize(filepath)
                _, ext = os.path.splitext(file)
                ext_lower = ext.lower()

                # Attempt to read a small text preview/snippet
                snippet = ""
                # Binary file extensions list to skip reading
                binary_exts = {
                    ".zip",
                    ".png",
                    ".jpg",
                    ".jpeg",
                    ".gif",
                    ".exe",
                    ".dll",
                    ".pdf",
                    ".mp3",
                    ".mp4",
                    ".mov",
                    ".xlsx",
                    ".docx",
                }

                if ext_lower in binary_exts:
                    snippet = f"[Binary/Media File: {ext_lower.upper()}]"
                else:
                    try:
                        with open(
                            filepath, "r", encoding="utf-8", errors="ignore"
                        ) as f:
                            snippet = f.read(500).strip()
                            # Clean up line breaks for display
                            snippet = re.sub(r"\s+", " ", snippet)[:300]
                    except Exception:
                        snippet = (
                            f"[Unable to read content snippet: {ext_lower.upper()}]"
                        )

                files_list.append(
                    FileInfo(
                        filepath=filepath,
                        filename=file,
                        extension=ext_lower or "no_extension",
                        snippet=snippet or "[Empty file]",
                        size_bytes=size_bytes,
                    )
                )
            except Exception as e:
                print(f"Warning: Skipping file {file} due to error: {e}")

    print(f"Discovered {len(files_list)} files for organization.")
    scan_res = ScanResult(
        source_dir=source_dir, destination_dir=destination_dir, files=files_list
    )
    return scan_res


# ==============================================================================
# DESIGN PATTERN: Graph-Based Workflow Node 2 (AI Node)
# ==============================================================================
# The Categorizer Agent is the intelligent node in the workflow graph, powered by
# Gemini-2.5-Flash. It uses schema-validated inputs (ScanResult) and outputs
# (CategorizationResult) to ensure absolute structural consistency.
#
# BEHAVIOR & SKILLS COUPLING:
# The agent is bound to a custom ADK Skill ('my-skill'). The skill acts as a set of
# developer-defined guidelines and heuristics that direct the LLM on folder naming,
# semantic groupings, and hierarchical depth, ensuring the output directory is 
# logical, professional, and intuitive.
#
# INTERCEPTOR HOOK:
# All tool invocations made by this agent are automatically intercepted by 
# 'security_before_tool_callback' (hooks.py), enforcing in-place PII redaction and 
# shell injection blocks before the execution layer processes them.
# ==============================================================================

# Load the local file categorization and organization skill guidelines
SKILLS_DIR = pathlib.Path(__file__).parent / "my-skill"
my_skill = load_skill_from_dir(SKILLS_DIR)
my_skill_toolset = SkillToolset(skills=[my_skill])

categorizer_agent = Agent(
    name="neaty_categorizer",
    model="gemini-2.5-flash",
    input_schema=ScanResult,
    output_schema=CategorizationResult,
    tools=[my_skill_toolset],
    before_tool_callback=security_before_tool_callback,
    instruction="""
    You are an expert filing assistant and librarian.
    Your task is to analyze the list of files provided in the ScanResult and organize them into neat, logical categories.
    
    You have access to a specialized skill tool named `my-skill` which contains the latest file organization guidelines and naming rules. Always refer to this skill to guide your classification decisions and directory naming.
    
    Guidelines:
    1. Group the files based on a blend of their file format, contents, and subject.
    2. For each category, you MUST generate a descriptive, beautiful, and "neat" folder name.
       - Bad folder names: "python", "docs", "scripts", "images".
       - Good folder names: "Core Python Helper Scripts", "Project Setup & Config", "Graphic Design Assets", "User Research & Surveys".
       - Make the folder names highly readable, professional, and descriptive based on the subjects detected in the content snippets.
    3. Make sure every single file in the list is assigned to exactly one category.
    4. Provide a clear 'explanation' for why the files are categorized together.
    5. Do not lose or omit any file from the input list.
    """,
)


# ==============================================================================
# DESIGN PATTERN: Graph-Based Workflow Node 3
# ==============================================================================
# The Safe Organize Files Node executes the actual folder operations designed by
# the LLM. It guarantees absolute file and metadata integrity.
#
# NON-DESTRUCTIVE SAFE COPY DESIGN:
# To prevent data loss, the agent never overwrites or alters the content of any
# user file. It operates strictly under a read-and-copy mechanism.
#
# METADATA PRESERVATION:
# By utilizing 'shutil.copy2' instead of basic 'shutil.copy', Neaty replicates
# file data while preserving historical file metadata (creation times, modified times,
# and file permissions). This prevents old family photos or tax documents from having
# their timestamps reset to "today," maintaining their chronological record.
# ==============================================================================


def organize_files_node(node_input: CategorizationResult) -> Event:
    """
    BEHAVIOR:
    Reads the category layout, creates target output subfolders safely,
    replicates files using metadata-preserving copy operations, and logs
    a structured execution summary in ORGANIZATION_REPORT.md.
    """
    destination_dir = node_input.destination_dir
    print(f"\n[Step 3] Organizing files into folders inside: {destination_dir}")

    summary_lines = []
    summary_lines.append("# Organization Report - Neaty Agent")
    summary_lines.append(f"- **Source**: {node_input.source_dir}")
    summary_lines.append(f"- **Destination**: {destination_dir}\n")
    summary_lines.append(
        "| Descriptive Folder Name | Format Group | Subject | Files Copied |"
    )
    summary_lines.append("| :--- | :--- | :--- | :--- |")

    total_copied = 0

    for category in node_input.categories:
        # Clean folder name to be valid for filesystems
        safe_folder_name = re.sub(
            r'[\\/*?:"<>|]', "", category.suggested_folder_name
        ).strip()
        # Keep name clean and not empty
        if not safe_folder_name:
            safe_folder_name = category.category_id

        target_folder = os.path.join(destination_dir, safe_folder_name)
        os.makedirs(target_folder, exist_ok=True)

        copied_files_in_category = []
        for filepath in category.filepaths:
            if not os.path.exists(filepath):
                print(f"Warning: File no longer exists, skipping: {filepath}")
                continue

            filename = os.path.basename(filepath)
            dest_filepath = os.path.join(target_folder, filename)

            try:
                # Use copy2 to preserve metadata (timestamps, etc.) and keep originals completely unchanged
                shutil.copy2(filepath, dest_filepath)
                copied_files_in_category.append(filename)
                total_copied += 1
            except Exception as e:
                print(f"Error copying {filename} to {safe_folder_name}: {e}")

        # Append to report
        summary_lines.append(
            f"| **{safe_folder_name}** | {category.format_type} | {category.subject} | {len(copied_files_in_category)} file(s) |"
        )
        for f in copied_files_in_category:
            print(f" -> Copied {f} to folder: {safe_folder_name}")

    summary_lines.append(
        f"\n**Successfully organized {total_copied} file(s) safely!** No source files were modified or deleted."
    )
    report_text = "\n".join(summary_lines)

    # Save the markdown report to the destination directory
    report_path = os.path.join(destination_dir, "ORGANIZATION_REPORT.md")
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report_text)

    print(f"\nSaved file organization report to: {report_path}")
    return Event(
        message=f"File organization complete. Organized {total_copied} files into descriptive folders.\nDetails saved to ORGANIZATION_REPORT.md",
        output=report_text,
    )


# ==========================================
# 5. Define the Workflow Graph & App
# ==========================================

neaty_workflow = Workflow(
    name="neaty_workflow",
    edges=[
        ("START", scan_directory_node),
        (scan_directory_node, categorizer_agent),
        (categorizer_agent, organize_files_node),
    ],
)

app = App(name="neaty_agent", root_agent=neaty_workflow)


# ==========================================
# 6. Command Line Interface Runner
# ==========================================


async def run_organizer(source_dir: str, destination_dir: Optional[str] = None):
    # Default destination to 'organized_output' inside source_dir if not specified
    if not destination_dir:
        destination_dir = os.path.join(source_dir, "organized_output")

    os.makedirs(destination_dir, exist_ok=True)

    # Ensure environment variables are loaded
    use_vertex = (
        os.getenv("GOOGLE_GENAI_USE_VERTEXAI", "").upper() in ("TRUE", "1")
        or os.getenv("GOOGLE_GENAI_USE_ENTERPRISE", "").upper() in ("TRUE", "1")
        or bool(os.getenv("GOOGLE_CLOUD_PROJECT"))
    )
    api_key = os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")
    if not api_key and not use_vertex:
        print(
            "\n[ERROR] Gemini API Key not found. Please ensure GEMINI_API_KEY is configured in your .env file, or configure Vertex AI / Google Cloud project environment variables."
        )
        return

    print("=" * 60)
    print("Neaty Agent — Graph-Based File Organization (ADK 2.0)")
    print("=" * 60)
    print(f"Source Directory:      {os.path.abspath(source_dir)}")
    print(f"Destination Directory: {os.path.abspath(destination_dir)}")
    print("=" * 60)

    runner = InMemoryRunner(app=app)

    # Construct the input to the workflow
    workflow_input = WorkflowInput(
        source_dir=source_dir, destination_dir=destination_dir
    )

    try:
        # Run workflow via the runner
        result = await runner.run_debug(workflow_input.model_dump_json())
        print("\n" + "=" * 60)
        print("WORKFLOW RUN SUCCESSFUL!")
        print("=" * 60)
        print(result)
    except Exception as e:
        import traceback

        traceback.print_exc()
        print("\n" + "=" * 60)
        print("WORKFLOW RUN FAILED!")
        print("=" * 60)
        print("An error occurred during workflow execution:", e)
        print(
            "\nNote: If you encountered a 429 Prepayment Credits error, please update your billing in Google AI Studio to resume API access."
        )


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Neaty Agent: Organize files into descriptive directories using ADK 2.0 and Gemini."
    )
    parser.add_argument(
        "--source",
        "-s",
        default=".",
        help="Source directory to organize (default: current directory)",
    )
    parser.add_argument(
        "--dest",
        "-d",
        default=None,
        help="Destination directory (default: 'organized_output' in source directory)",
    )

    args = parser.parse_args()

    # Run the async runner
    asyncio.run(run_organizer(args.source, args.dest))
